#!/usr/bin/env bash

set -xeuo pipefail

yum install -y gcc make

rm -rf sqlite sqlite3
mkdir -p sqlite

curl -fsSL https://sqlite.org/2024/sqlite-autoconf-3450100.tar.gz \
  | tar -C sqlite -xz --strip-components=1

cd sqlite
./configure
make
chown 1000:1000 sqlite3
mv sqlite3 ../
cd ..

strip sqlite3
