name: release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    container: centos:6.10
    steps:
      - name: Build
        run: |
          yum install -y gcc
          mkdir sqlite
          cd sqlite
          curl -fsSL https://sqlite.org/2020/sqlite-autoconf-${{ github.ref }}.tar.gz | tar -xz --strip-components=1
          ./configure
          make
          chown 1000:1000 sqlite3
          cp sqlite3 ../

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sqlite3
          asset_name: sqlite3
          asset_content_type: application/x-executable
